# To run this file, you'll need private http client environment file. Ask from your team mates.

POST https://login.microsoftonline.com/{{tenantId}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

client_id={{clientId}}&grant_type=client_credentials&scope= {{clientId}}/.default&client_secret={{clientSecret}}


> {%
  client.global.set("tis_token", response.body.access_token)
%}

###

POST localhost:8080/api/company
Content-Type: application/json

{
    "businessId": "1111111-1",
    "name": "Firsty Firstings Ltd"
}

###

POST localhost:8080/api/company
Content-Type: application/json

{
    "businessId": "2222222-2",
    "name": "Seccu Secundings Ltd"
}

###

POST localhost:8080/api/partnership
Content-Type: application/json

{
  "type": "AUTHORITY_PROVIDER",
  "partnerABusinessId": "1111111-1",
  "partnerBBusinessId": "2222222-2"
}
