# To run this file, you'll need private http client environment file. Ask from your team mates.

POST https://login.microsoftonline.com/{{tenantId}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

client_id={{clientId}}&grant_type=client_credentials&scope={{scope}}&client_secret={{clientSecret}}


> {%
  client.global.set("tis_token", response.body.access_token)
%}

###

POST {{serviceRootUri}}/api/company
Content-Type: application/json
Authorization: Bearer {{tis_token}}

{
    "businessId": "1111111-1",
    "name": "Firsty Firstings Ltd",
    "publish": false
}

###

POST {{serviceRootUri}}/api/company
Content-Type: application/json
Authorization: Bearer {{tis_token}}

{
    "businessId": "2222222-2",
    "name": "Seccu Secundings Ltd",
    "publish": false
}

###

POST {{serviceRootUri}}/api/partnership
Content-Type: application/json
Authorization: Bearer {{tis_token}}

{
  "type": "AUTHORITY_PROVIDER",
  "partnerABusinessId": "1111111-1",
  "partnerBBusinessId": "2222222-2"
}
###

POST {{serviceRootUri}}/api/partnership
Content-Type: application/json
Authorization: Bearer {{tis_token}}

{
  "type": "AUTHORITY_PROVIDER",
  "partnerABusinessId": "2942108-7",
  "partnerBBusinessId": "1111111-1"
}
