POST http://localhost:8080/api/queue
Content-Type: application/json

{
  "url": "http://localhost:8080/api/static/testfiles/padasjoen_kunta.zip",
  "format": "gtfs",
  "businessId": "2942108-7",
  "etag": "etagg",
  "validations": [
    {
      "name": "gtfs.canonical.v4_0_0",
      "config": {
        "lol": "apua",
        "muumi": "pappa"
      }
    }
  ],
  "conversions": [
  ],
  "metadata": {
    "brewingEquipment": "teapot",
    "capacity (ml)": 1500,
    "tea": "Yorkshire Tea"
  }
}

> {%
    client.global.set("entry_details_link", response.body.links.self.href)
%}

###

GET {{entry_details_link}}
Content-Type: application/json
