version: '3.8'

name: 'tis'

services:
  db:
    container_name: '${COMPOSE_PROJECT_NAME}_postgresql15'
    image: postgres:15-bullseye
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dwULL632mdJZ
      POSTGRES_DB: vaco
    ports:
      - "54321:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: '${COMPOSE_PROJECT_NAME}_pgadmin14'
    image: dpage/pgadmin4:6
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: noreply@solita.fi
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5480:80"
    depends_on:
      - db

  localstack:
    container_name: "${COMPOSE_PROJECT_NAME}_localstack_main"
    image: localstack/localstack:2.0.2
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DISABLE_EVENTS=1
      - SERVICES=sqs
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
      - AWS_DEFAULT_REGION=eu-central-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "./init-localstack.sh:/etc/localstack/init/ready.d/init-localstack.sh"

volumes:
  postgres-data:
