# common steps and such for setting up the required dependencies for VACO backend
# main reason this exists is to allow for parallel execution of Sonar alongside the main test verifications

name: Setup project tools and dependencies

inputs:
  deploy-key:
    required: true
    type: string

runs:
  using: composite

  steps:
    - name: Checkout database migrations
      uses: ./digitraffic-tis-vaco/.github/actions/checkout
      with:
        repository: tmfg/digitraffic-tis-dbmigrator
        path: digitraffic-tis-dbmigrator
        deploy-key: ${{ inputs.deploy-key }}
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version-file: './digitraffic-tis-vaco/.java-version'
        distribution: 'temurin'
    
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2