# To run this file, you'll need private http client environment file. Ask from your team mates.

POST https://login.microsoftonline.com/{{tenantId}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

client_id={{clientId}}&grant_type=client_credentials&scope={{scope}}&client_secret={{clientSecret}}


> {%
  client.global.set("tis_token", response.body.access_token)
%}

###

POST {{serviceRootUri}}/api/queue
Content-Type: application/json
Authorization: Bearer {{tis_token}}

{
  "url": "https://minfoapi.matkahuolto.fi/gtfs/4820/gtfs.zip",
  "format": "gtfs",
  "businessId": "2942108-7",
  "name": "TIS-683 bugtest Skiigge Boi Edition",
  "conversions": [{
    "name": "gtfs2netex.fintraffic",
    "config": {}
  }],
  "metadata": {}
}

> {%
  client.global.set("entry_details_link", response.body.links.refs.self.href)
%}

###

GET {{entry_details_link}}
Content-Type: application/json


###

POST {{serviceRootUri}}/api/feeds/iA3ieKn8MU5rw9a5O9LWv/true
Content-Type: application/json
Authorization: Bearer {{tis_token}}

###

POST {{serviceRootUri}}/api/feeds
Content-Type: application/json
Authorization: Bearer {{tis_token}}

{
  "owner": "2942108-7",
  "uri": {
    "uri": "http://example.com",
    "queryParams": {"param1": "value1"},
    "httpMethod": "POST",
    "requestBody": ""
  },
  "processingEnabled": false,
  "format" : "SIRI_SX"
}

###

GET {{serviceRootUri}}/api/feeds
Content-Type: application/json
Authorization: Bearer {{tis_token}}

###

DELETE {{serviceRootUri}}/api/feeds/iA3ieKn8MU5rw9a5O9LWv
Content-Type: application/json
Authorization: Bearer {{tis_token}}





