# To run this file, you'll need private http client environment file. Ask from your team mates.

POST https://login.microsoftonline.com/{{tenantId}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

client_id={{clientId}}&grant_type=client_credentials&scope={{scope}}&client_secret={{clientSecret}}


> {%
  client.global.set("tis_token", response.body.access_token)
%}

###

POST {{serviceRootUri}}/api/queue
Content-Type: application/json
Authorization: Bearer {{tis_token}}

{
  "url": "https://tvv.fra1.digitaloceanspaces.com/211_netex.zip",
  "format": "netex",
  "businessId": "2942108-7",
  "etag": "etagg",
  "name": "NeTEx Kajaani local",
  "validations": [
    {
      "name": "netex.entur",
      "config": {
        "codespace": "FIN",
        "reportId": "NO_REPORT_ID",
        "ignorableNetexElements": ["SiteFrame"],
        "maximumErrors": 128
      }
    }
  ],
  "conversions": [
  ],
  "metadata": {
    "brewingEquipment": "teapot",
    "capacity (ml)": 700,
    "tea": "Twinings Gold"
  }
}

> {%
    client.global.set("entry_details_link", response.body.links.refs.self.href)
%}

###

GET {{entry_details_link}}
Content-Type: application/json
