name: Verify Commit
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version-file: '.java-version'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: mvn test

      - name: Publish Test Report
        if: always()
        uses: scacap/action-surefire-report@v1
