name: Verify Commit
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  checks: write  # required by scacap/action-surefire-report
  contents: read  # required by scacap/action-surefire-report

jobs:
  build:
    name: Verify Pull Request
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./digitraffic-tis-vaco
    steps:
      - name: Checkout project files
        uses: actions/checkout@v3
        with:
          path: digitraffic-tis-vaco

      - name: Checkout database migrations
        uses: actions/checkout@v3
        with:
          repository: tmfg/digitraffic-tis-dbmigrator
          ssh-key: ${{ secrets.DBMIGRATOR_DEPLOY_KEY }}
          path: digitraffic-tis-dbmigrator

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version-file: './digitraffic-tis-vaco/.java-version'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: mvn test

      - name: Publish Test Report
        if: always()
        uses: scacap/action-surefire-report@v1
