name: Releases

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout project files
        uses: actions/checkout@v3
        with:
          path: digitraffic-tis-vaco
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version-file: '.java-version'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B --show-version validate
      - name: Show git information
        run: |
          git status
          git log --no-color --graph --oneline -n 10
          git tag --list
